// packages/react/src/ChromePicker.tsx
import {
  ChromePicker as CorePicker,
  type ChromePickerOptions,
} from '@dayflow/blossom-color-picker';
import { useRef, useEffect, forwardRef, type ForwardedRef } from 'react';

export interface ChromePickerProps extends ChromePickerOptions {
  className?: string;
}

function propsToOptions(
  props: ChromePickerProps
): Partial<ChromePickerOptions> {
  const opts: Partial<ChromePickerOptions> = {};

  if (props.value !== undefined) opts.value = props.value;
  if (props.defaultValue !== undefined) opts.defaultValue = props.defaultValue;
  if (props.colors !== undefined) opts.colors = props.colors;
  if (props.onChange !== undefined) opts.onChange = props.onChange;
  if (props.onCollapse !== undefined) opts.onCollapse = props.onCollapse;
  if (props.disabled !== undefined) opts.disabled = props.disabled;
  if (props.openOnHover !== undefined) opts.openOnHover = props.openOnHover;
  if (props.initialExpanded !== undefined)
    opts.initialExpanded = props.initialExpanded;
  if (props.animationDuration !== undefined)
    opts.animationDuration = props.animationDuration;
  if (props.showAlphaSlider !== undefined)
    opts.showAlphaSlider = props.showAlphaSlider;
  if (props.coreSize !== undefined) opts.coreSize = props.coreSize;
  if (props.petalSize !== undefined) opts.petalSize = props.petalSize;
  if (props.showCoreColor !== undefined)
    opts.showCoreColor = props.showCoreColor;
  if (props.sliderPosition !== undefined)
    opts.sliderPosition = props.sliderPosition;
  if (props.adaptivePositioning !== undefined)
    opts.adaptivePositioning = props.adaptivePositioning;
  if (props.circularBarWidth !== undefined)
    opts.circularBarWidth = props.circularBarWidth;
  if (props.sliderWidth !== undefined) opts.sliderWidth = props.sliderWidth;
  if (props.sliderOffset !== undefined) opts.sliderOffset = props.sliderOffset;
  if (props.collapsible !== undefined) opts.collapsible = props.collapsible;
  if (props.darkMode !== undefined) opts.darkMode = props.darkMode;
  if (props.darkModeColors !== undefined)
    opts.darkModeColors = props.darkModeColors;

  return opts;
}

export const ChromePicker = forwardRef(function ChromePicker(
  props: ChromePickerProps,
  ref: ForwardedRef<HTMLDivElement>
) {
  const containerRef = useRef<HTMLDivElement>(null);
  const pickerRef = useRef<CorePicker | null>(null);

  // Mount core instance
  useEffect(() => {
    if (!containerRef.current) return;
    pickerRef.current = new CorePicker(
      containerRef.current,
      propsToOptions(props)
    );
    return () => {
      pickerRef.current?.destroy();
      pickerRef.current = null;
    };
  }, []);

  useEffect(() => {
    pickerRef.current?.setOptions({
      value: props.value,
      onChange: props.onChange,
      onCollapse: props.onCollapse,
    });
  }, [props.value, props.onChange, props.onCollapse]);

  useEffect(() => {
    pickerRef.current?.setOptions(propsToOptions(props));
  }, [
    props.colors,
    props.disabled,
    props.openOnHover,
    props.initialExpanded,
    props.animationDuration,
    props.showAlphaSlider,
    props.coreSize,
    props.petalSize,
    props.showCoreColor,
    props.sliderPosition,
    props.adaptivePositioning,
    props.circularBarWidth,
    props.sliderWidth,
    props.sliderOffset,
    props.collapsible,
    props.darkMode,
    props.darkModeColors,
  ]);

  // Forward ref
  useEffect(() => {
    if (!ref) return;
    if (typeof ref === 'function') {
      ref(containerRef.current);
    } else {
      ref.current = containerRef.current;
    }
  }, [ref]);

  return <div ref={containerRef} className={props.className} />;
});

export default ChromePicker;

// packages/svelte/src/ChromePicker.svelte
<script lang="ts">
  import {
    ChromePicker as CorePicker,
    type ChromePickerOptions,
    type BlossomColorPickerValue,
    type ColorInput,
    type SliderPosition,
    type BlossomColorPickerColor,
    type ChromePickerThemeColors
  } from '@dayflow/blossom-color-picker';
  import { onMount } from 'svelte';

  interface Props {
    value?: BlossomColorPickerValue;
    defaultValue?: BlossomColorPickerValue;
    colors?: ColorInput[];
    disabled?: boolean;
    openOnHover?: boolean;
    initialExpanded?: boolean;
    animationDuration?: number;
    showAlphaSlider?: boolean;
    coreSize?: number;
    petalSize?: number;
    showCoreColor?: boolean;
    sliderPosition?: SliderPosition;
    adaptivePositioning?: boolean;
    circularBarWidth?: number;
    sliderWidth?: number;
    sliderOffset?: number;
    collapsible?: boolean;
    darkMode?: boolean;
    darkModeColors?: Partial<ChromePickerThemeColors>;
    class?: string;
    onchange?: (color: BlossomColorPickerColor) => void;
    oncollapse?: (color: BlossomColorPickerColor) => void;
  }

  let {
    value = undefined,
    defaultValue = undefined,
    colors = undefined,
    disabled = false,
    openOnHover = false,
    initialExpanded = false,
    animationDuration = 300,
    showAlphaSlider = true,
    coreSize = 32,
    petalSize = 32,
    showCoreColor = true,
    sliderPosition = undefined,
    adaptivePositioning = true,
    circularBarWidth = undefined,
    sliderWidth = undefined,
    sliderOffset = undefined,
    collapsible = false,
    darkMode = undefined,
    darkModeColors = undefined,
    class: className = '',
    onchange = undefined,
    oncollapse = undefined,
  }: Props = $props();

  let container: HTMLDivElement;
  let picker: CorePicker | null = null;

  function getOptions(): ChromePickerOptions {
    return {
      value,
      defaultValue,
      colors,
      disabled,
      openOnHover,
      initialExpanded,
      animationDuration,
      showAlphaSlider,
      coreSize,
      petalSize,
      showCoreColor,
      sliderPosition,
      adaptivePositioning,
      circularBarWidth,
      sliderWidth,
      sliderOffset,
      collapsible,
      darkMode,
      darkModeColors,
      onChange: onchange,
      onCollapse: oncollapse,
    };
  }

  onMount(() => {
    picker = new CorePicker(container, getOptions());
    return () => {
      picker?.destroy();
      picker = null;
    };
  });

  $effect(() => {
    if (picker) {
      picker.setOptions(getOptions());
    }
  });
</script>

<div bind:this={container} class={className}></div>
