// packages/svelte/src/BlossomColorPicker.svelte
<script lang="ts">
  import {
    BlossomColorPicker as CorePicker,
    type BlossomColorPickerOptions,
    type BlossomColorPickerValue,
    type ColorInput,
    type SliderPosition,
    type BlossomColorPickerColor
  } from '@dayflow/blossom-color-picker';
  import { onMount } from 'svelte';

  interface Props {
    value?: BlossomColorPickerValue;
    defaultValue?: BlossomColorPickerValue;
    colors?: ColorInput[];
    disabled?: boolean;
    openOnHover?: boolean;
    initialExpanded?: boolean;
    animationDuration?: number;
    showAlphaSlider?: boolean;
    coreSize?: number;
    petalSize?: number;
    showCoreColor?: boolean;
    sliderPosition?: SliderPosition;
    adaptivePositioning?: boolean;
    circularBarWidth?: number;
    sliderWidth?: number;
    sliderOffset?: number;
    collapsible?: boolean;
    class?: string;
    onchange?: (color: BlossomColorPickerColor) => void;
    oncollapse?: (color: BlossomColorPickerColor) => void;
  }

  let {
    value = undefined,
    defaultValue = undefined,
    colors = undefined,
    disabled = false,
    openOnHover = false,
    initialExpanded = false,
    animationDuration = 300,
    showAlphaSlider = true,
    coreSize = 32,
    petalSize = 32,
    showCoreColor = true,
    sliderPosition = undefined,
    adaptivePositioning = true,
    circularBarWidth = undefined,
    sliderWidth = undefined,
    sliderOffset = undefined,
    collapsible = true,
    class: className = '',
    onchange = undefined,
    oncollapse = undefined,
  }: Props = $props();

  let container: HTMLDivElement;
  let picker: CorePicker | null = null;

  function getOptions(): BlossomColorPickerOptions {
    return {
      value,
      defaultValue,
      colors,
      disabled,
      openOnHover,
      initialExpanded,
      animationDuration,
      showAlphaSlider,
      coreSize,
      petalSize,
      showCoreColor,
      sliderPosition,
      adaptivePositioning,
      circularBarWidth,
      sliderWidth,
      sliderOffset,
      collapsible,
      onChange: onchange,
      onCollapse: oncollapse,
    };
  }

  onMount(() => {
    picker = new CorePicker(container, getOptions());
    return () => {
      picker?.destroy();
      picker = null;
    };
  });

  $effect(() => {
    if (picker) {
      picker.setOptions(getOptions());
    }
  });
</script>

<div bind:this={container} class={className}></div>

// packages/angular/src/lib/blossom-color-picker.component.ts
import '@dayflow/blossom-color-picker/styles.css';
import {
  Component,
  ElementRef,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  AfterViewInit,
  OnDestroy,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import {
  BlossomColorPicker as CorePicker,
  type BlossomColorPickerOptions,
  type BlossomColorPickerValue,
  type BlossomColorPickerColor,
  type ColorInput,
  type SliderPosition,
} from '@dayflow/blossom-color-picker';

@Component({
  selector: 'blossom-color-picker',
  standalone: true,
  template: '<div #container></div>',
})
export class BlossomColorPickerComponent
  implements AfterViewInit, OnDestroy, OnChanges
{
  @ViewChild('container', { static: true })
  containerRef!: ElementRef<HTMLDivElement>;

  @Input() value?: BlossomColorPickerValue;
  @Input() defaultValue?: BlossomColorPickerValue;
  @Input() colors?: ColorInput[];
  @Input() disabled = false;
  @Input() openOnHover = false;
  @Input() initialExpanded = false;
  @Input() animationDuration = 300;
  @Input() showAlphaSlider = true;
  @Input() coreSize = 32;
  @Input() petalSize = 32;
  @Input() showCoreColor = true;
  @Input() sliderPosition?: SliderPosition;
  @Input() adaptivePositioning = true;
  @Input() circularBarWidth?: number;
  @Input() sliderWidth?: number;
  @Input() sliderOffset?: number;
  @Input() collapsible = true;

  @Output() colorChange = new EventEmitter<BlossomColorPickerColor>();
  @Output() colorCollapse = new EventEmitter<BlossomColorPickerColor>();

  private picker: CorePicker | null = null;

  ngAfterViewInit(): void {
    this.picker = new CorePicker(
      this.containerRef.nativeElement,
      this.getOptions()
    );
  }

  ngOnDestroy(): void {
    this.picker?.destroy();
    this.picker = null;
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.picker) return;

    // Only send value + callbacks for value-only changes (cheap update)
    if (changes['value'] && Object.keys(changes).length === 1) {
      this.picker.setOptions({
        value: this.value,
        onChange: color => this.colorChange.emit(color),
        onCollapse: color => this.colorCollapse.emit(color),
      });
      return;
    }

    this.picker.setOptions(this.getOptions());
  }

  private getOptions(): BlossomColorPickerOptions {
    return {
      value: this.value,
      defaultValue: this.defaultValue,
      colors: this.colors,
      disabled: this.disabled,
      openOnHover: this.openOnHover,
      initialExpanded: this.initialExpanded,
      animationDuration: this.animationDuration,
      showAlphaSlider: this.showAlphaSlider,
      coreSize: this.coreSize,
      petalSize: this.petalSize,
      showCoreColor: this.showCoreColor,
      sliderPosition: this.sliderPosition,
      adaptivePositioning: this.adaptivePositioning,
      circularBarWidth: this.circularBarWidth,
      sliderWidth: this.sliderWidth,
      sliderOffset: this.sliderOffset,
      collapsible: this.collapsible,
      onChange: color => this.colorChange.emit(color),
      onCollapse: color => this.colorCollapse.emit(color),
    };
  }
}
